channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21
  - scipy=1.7
  - pandas=1.3
  - scikit-learn=1.0
  - matplotlib=3.4
  - networkx=2.6
  - requests
  - pip
  - tqdm
# Dev stuff
  - ipykernel
  - jupyter
  - black
  - pylint
  - flake8
